import { z } from "zod";
import { type Role, roleSchema } from "./schema";

export const roles: Role[] = z.array(roleSchema).parse([
  {
    slug: "procedure-tech",
    title: "Principal Software Engineer",
    company: "Procedure Tech",
    location: "Mumbai, India (Remote)",
    start: "2021-07",
    end: null,
    summary:
      "Lead AI-native development, agentic architecture design and full-stack platform engineering across multiple client products.",
    tags: ["ai", "design-systems", "frontend", "backend", "infra"],
    engagements: [
      {
        slug: "hive",
        client: "RoomAngel",
        product: "Hive",
        current: true,
        caseStudy: true,
        summary:
          "Forward Deployed Engineer building AI-native infrastructure and agentic harnesses for hospitality operations.",
        highlights: [
          "Built AI-native infrastructure and agentic harnesses for hospitality operations across both frontend and backend.",
          "Integrated third-party hospitality platforms (Opera Cloud, MyCloud) with full multi-tenancy support.",
          "Delivered features that surface hotel revenue and revenue-center insights through a natural-language chat interface.",
          "Built custom agents implementing agentic looping to automate repetitive chat-driven tasks.",
          "Authored custom agents, skills, hooks and orchestration so a single command implements an entire feature across backend, frontend and infrastructure.",
        ],
        metrics: [
          { value: "2-3 days", label: "feature delivery, down from weeks" },
          { value: "98%", label: "accuracy" },
          { value: "0", label: "rework" },
        ],
        tech: [
          "Agentic AI",
          "MCP",
          "Multi-Agent Orchestration",
          "RAG",
          "Claude Code",
          "Python (FastAPI)",
          "TypeScript",
          "Next.js",
          "React",
          "Node.js",
          "MongoDB",
          "Cloud Infrastructure",
          "Opera Cloud API",
          "MyCloud API",
          "Multi-Tenancy",
        ],
        tags: ["ai", "frontend", "backend", "infra"],
      },
      {
        slug: "brightlifecare",
        client: "BrightlifeCare (HealthKart)",
        product: "System Architecture & Design System Migration",
        caseStudy: true,
        brands: [
          "HealthKart",
          "MuscleBlaze",
          "Gritzo",
          "FuelOne",
          "TrueBasics",
          "HK Vitals",
          "Ronnie Coleman",
          "Incredio",
          "Smash",
        ],
        summary:
          "Architected a multi-brand React component library with dynamic theming across nine product lines.",
        highlights: [
          "Architected a multi-brand React component library with dynamic theming across 9 product lines.",
          "Built on atomic design principles with Tailwind CSS, Storybook documentation and full accessibility compliance.",
          "Designed RAG pipelines, multi-agent orchestration and MCP integrations to accelerate component development.",
          "Authored custom agent skills encoding architectural patterns, coding standards and domain knowledge, so agents generate context-aware production-ready code with minimal intervention.",
          "Implemented guardrails and a knowledge dependency graph to enforce architectural consistency.",
          "Engineered a plug-and-play design system, eliminating per-product manual overrides across all 9 products.",
          "Optimized Core Web Vitals, improving page load times, SEO and Google ranking signals.",
          "Led and mentored developers on the shared architecture, with unit and end-to-end test coverage.",
        ],
        metrics: [
          { value: "9", label: "products unified" },
          { value: "-70%", label: "token usage" },
          { value: "0", label: "per-product overrides" },
        ],
        tech: [
          "React",
          "TypeScript",
          "Tailwind CSS",
          "Storybook",
          "Vitest",
          "Playwright",
          "RAG Pipelines",
          "MCP",
          "Multi-Agent Orchestration",
          "Agent Skills",
          "Claude Code",
          "Atomic Design",
          "Core Web Vitals",
        ],
        tags: ["design-systems", "ai", "frontend"],
      },
      {
        slug: "pine-labs",
        client: "Pine Labs",
        product: "Payment Services",
        summary:
          "Shipped white-labelling for partner banks and mentored a junior engineer through the sprint pipeline.",
        highlights: [
          "Implemented a white-labelling feature supporting partner theming (CITI Bank), reducing theming setup time through a standardized global SCSS architecture.",
          "Mentored a junior engineer and managed execution of incoming features across sprints.",
        ],
        metrics: [],
        tech: ["React", "SCSS", "JavaScript", "CSS Custom Properties", "Git"],
        tags: ["design-systems", "frontend"],
      },
      {
        slug: "bitespeed",
        client: "Bitespeed",
        product: "Multichannel Marketing for Shopify Brands",
        caseStudy: true,
        summary:
          "Built a Web and Mobile Push Notification service end to end on AWS Serverless, handling broadcast notifications and webhooks at scale.",
        highlights: [
          "Built a Web Push and Mobile Push Notification service end-to-end on AWS Serverless, handling broadcast notifications and webhooks at scale.",
          "Engineered multi-vendor configuration handling and cron-based template fetching for broadcast messaging.",
          "Created a React Native mobile SDK for FCM push notifications on the Shopify mobile app.",
          "Developed a Lambda Authorizer securing all REST and Lambda API endpoints.",
          "Built a Postmaster tool for automated domain verification in email broadcast workflows.",
        ],
        metrics: [],
        tech: [
          "AWS Lambda",
          "Serverless Framework",
          "React Native",
          "FCM",
          "Node.js",
          "Cron",
          "REST APIs",
          "Shopify API",
        ],
        tags: ["backend", "infra", "mobile"],
      },
      {
        slug: "commandk",
        client: "CommandK",
        product: "Secrets Manager (Cybersecurity)",
        summary:
          "Built reusable frontend surface and a JSON-driven form engine for a cybersecurity secrets platform.",
        highlights: [
          "Built reusable frontend components for the Secrets Manager platform.",
          "Created a JSON-driven dynamic form generator with auto-generated validations via a custom transformer.",
          "Implemented Playwright end-to-end testing in Docker for automated regression coverage.",
        ],
        metrics: [],
        tech: ["React", "TypeScript", "Playwright", "Docker", "JSON Schema"],
        tags: ["design-systems", "frontend"],
      },
      {
        slug: "paytm",
        client: "Paytm",
        product:
          "Bank Statement Analysis, Free Credit Score, E-Raktkosh, Internal Tools",
        summary:
          "Owned frontend for two consumer finance products and shipped a government blood-donation mini app solo.",
        highlights: [
          "Owned frontend development for Bank Statement Analysis and Free Credit Score, managing a team of 3 developers.",
          "Resolved performance bottlenecks, improving application scalability and load times.",
          "Built the E-Raktkosh mini app (government blood donation platform) end-to-end as sole developer.",
          "Shipped bug fixes and new features on Paytm's internal admin panel.",
        ],
        metrics: [{ value: "3", label: "developers led" }],
        tech: [
          "React",
          "JavaScript",
          "HTML",
          "CSS",
          "REST APIs",
          "Performance Optimization",
        ],
        tags: ["frontend"],
      },
      {
        slug: "treebo",
        client: "Treebo Hotels",
        product: "Hotel Superhero (Hotel & Restaurant Management)",
        summary:
          "Frontend work on the POS system, plus a WebSocket thermal-printer integration proof of concept.",
        highlights: [
          "Implemented frontend features and bug fixes on the POS system.",
          "Built a thermal printer integration proof of concept using WebSockets with multi-printer network configuration.",
        ],
        metrics: [],
        tech: [
          "React",
          "JavaScript",
          "WebSockets",
          "Thermal Printer SDK",
          "POS Systems",
        ],
        tags: ["frontend"],
      },
    ],
  },
  {
    slug: "docmydoc",
    title: "Senior Mobile Development Engineer",
    company: "DocMyDoc",
    location: "Bengaluru, India",
    start: "2020-11",
    end: "2021-06",
    tags: ["mobile"],
    highlights: [
      "Developed and deployed the iOS app to production and executed a full UI refresh across Android and iOS from Figma designs.",
      "Built a custom web viewer component for unified image and PDF document viewing.",
      "Delivered a COVID-19 vaccination tracker, vitals tracker, document upload and action sliders.",
      "Owned release management (build, test, deploy) for both platforms with regression test coverage.",
    ],
    tech: [
      "React Native",
      "JavaScript",
      "iOS (Swift, Xcode)",
      "Android",
      "Figma",
      "Firebase",
      "PDF.js",
      "Regression Testing",
    ],
  },
  {
    slug: "trabacus",
    title: "Technical Associate",
    company: "Trabacus Technologies Pvt Ltd",
    location: "Bengaluru, India",
    start: "2020-03",
    end: "2020-11",
    tags: ["mobile"],
    highlights: [
      "Built an Instagram Story clone for the social media module integrated with the BookNGogo travel platform.",
      "Developed cross-platform mobile apps in React Native using Redux, React Navigation and gesture animations.",
      "Managed release builds for Android and TestFlight; diagnosed and fixed performance bottlenecks.",
    ],
    tech: [
      "React Native",
      "Redux",
      "React Navigation",
      "JavaScript",
      "Android",
      "iOS (TestFlight)",
    ],
  },
  {
    slug: "adinav-labs",
    title: "Project Manager & React Native Developer",
    company: "Adinav Labs Private Limited",
    location: "Bengaluru, India",
    start: "2019-04",
    end: "2020-03",
    tags: ["mobile", "infra"],
    highlights: [
      "Built reusable UI components in React Native for the Kafezz and Protia apps; configured AWS infrastructure (S3, SES, SNS).",
      "Managed a development team to deliver milestones on schedule and owned release management for Android and iOS.",
    ],
    tech: [
      "React Native",
      "Firebase",
      "AWS (S3, SES, SNS)",
      "JavaScript",
      "Android",
      "iOS",
      "Release Management",
    ],
  },
]);

export const engagements = roles.flatMap((role) =>
  role.engagements.map((engagement) => ({ ...engagement, role })),
);

export const caseStudySlugs = engagements
  .filter((engagement) => engagement.caseStudy)
  .map((engagement) => engagement.slug);
