import { z } from "zod";
import { type SkillGroup, skillGroupSchema } from "./schema";

/**
 * Order is deliberate. /about lays these out two to a row, so groups of a
 * similar length sit next to each other - otherwise a three-line group pairs
 * with a one-line group and the row leaves a hole under the short one.
 */
export const skillGroups: SkillGroup[] = z.array(skillGroupSchema).parse([
  {
    slug: "ai",
    label: "AI & Agentic Systems",
    items: [
      "Agentic AI",
      "Multi-Agent Orchestration",
      "RAG Pipelines",
      "MCP (Model Context Protocol)",
      "Agent Skills",
      "Knowledge Graphs",
      "Prompt Engineering",
      "Guardrails",
      "LLM Integration",
      "Anthropic API",
      "Claude Code",
      "Codex CLI",
      "Cursor",
    ],
  },
  {
    slug: "frontend",
    label: "Frontend",
    items: [
      "TypeScript",
      "JavaScript",
      "React",
      "Next.js",
      "Redux",
      "Tailwind CSS",
      "SCSS",
      "Storybook",
      "Design Systems",
      "Atomic Design",
      "Component Libraries",
      "Accessibility (a11y)",
      "Core Web Vitals",
      "SEO",
      "Performance Optimization",
    ],
  },
  {
    slug: "backend",
    label: "Backend & Data",
    items: [
      "Node.js",
      "Python",
      "FastAPI",
      "REST APIs",
      "GraphQL",
      "WebSockets",
      "MongoDB",
      "Firebase",
    ],
  },
  {
    slug: "testing",
    label: "Testing & Tooling",
    items: [
      "Vitest",
      "Playwright",
      "Git",
      "GitHub Actions",
      "CI/CD",
      "Turborepo",
      "pnpm",
      "Monorepo",
      "npm Publishing",
      "CLI Tooling",
      "Figma",
      "Figma MCP",
    ],
  },
  {
    slug: "cloud",
    label: "Cloud & Infrastructure",
    items: [
      "GCP",
      "AWS (Lambda, S3, SES, SNS)",
      "Serverless Framework",
      "Docker",
      "Docker Compose",
      "Nix",
      "Nix Flakes",
      "Home Manager",
      "nix-darwin",
      "WSL2",
      "Shell Scripting",
      "Reproducible Builds",
    ],
  },
  {
    slug: "leadership",
    label: "Leadership & Practice",
    items: [
      "System Architecture",
      "Technical Leadership",
      "Team Mentorship",
      "Agile",
      "Sprint Planning",
      "Release Management",
      "Stakeholder Communication",
      "Open Source Maintenance",
    ],
  },
  {
    slug: "mobile",
    label: "Mobile",
    items: [
      "React Native",
      "iOS (Swift, Xcode, TestFlight)",
      "Android",
      "FCM Push Notifications",
    ],
  },
  {
    slug: "web3",
    label: "Web3",
    items: [
      "Zero-Knowledge Proofs",
      "Groth16",
      "Circom",
      "Solidity",
      "EVM",
      "Polygon",
    ],
  },
]);

/** Flat, de-duplicated marquee source for the home page. */
export const marqueeSkills = [
  "Agentic AI",
  "MCP",
  "RAG",
  "Multi-Agent Orchestration",
  "Next.js",
  "React",
  "TypeScript",
  "Python",
  "FastAPI",
  "Node.js",
  "MongoDB",
  "Tailwind CSS",
  "Storybook",
  "Playwright",
  "GCP",
  "AWS",
  "Docker",
  "Nix",
  "React Native",
  "Circom",
  "Solidity",
];
